Fix packaging issue and <drm/drm.h> include directive
amd/xdna-driver pull request #169
Opened 2024-07-22 18:33 UTC by xuwd1

* Remove quotes in the Linux flavor string
* Change the amdxdna_accel.h header to conditionally include <drm/drm.h> or <libdrm/drm.h>: ** Including <drm/drm.h> is fine in compiling the kernel module ** However this will cause a missing header error with default compiler include path setting, while including kernel header into userspace code is considered bad. Thus <libdrm/drm.h> should be used for the userspace lib.
* Change "amd-aie" to "xdna-driver" in the README.md

2024-07-22 20:42 UTC, maxzhen commented
The change 1 and 3 looks sane. But change #2 does not look right. We did the same as other drm drivers do. I don't see any one using drm.h from libdrm directory. Maybe you're missing linux header package or libc package matching the kernel you're using? BTW, you need to use 6.10 kernel source now.

2024-07-22 20:43 UTC, maxzhen requested changes
See my comment above.

2024-07-22 21:18 UTC, xuwd1 commented
To justify my changes and explain in more detail:
1. Yes I'm currently on `6.10.0-1-mainline`. I built this new version of the kernel specifically for this driver.
2. I'm pretty sure it's not because I have missing headers. <drm/drm.h> is a kernel header which should resides in `/usr/lib/modules/$(uname -r)/build/include/uapi/`, which is strictly a kernel header and should not be introduced into the userspace code. I see that in this repo, the reason <drm/drm.h> is used is that the library needs its macro definition and some other struct defs. In such case, <libdrm/drm.h> should be used, which is exactly the reason libdrm exists. 
3. For a more concrete example of libdrm is used as a replacement for the kernel header in userspace code, `xrt/src/runtime_src/core/edge/include/zynq_ioctl.h` is a good case.

2024-07-22 21:47 UTC, maxzhen commented
> To justify my changes and explain in more detail:
> 
> 1. Yes I'm currently on `6.10.0-1-mainline`. I built this new version of the kernel specifically for this driver.
> 2. I'm pretty sure it's not because I have missing headers. <drm/drm.h> is a kernel header which should reside in `/usr/lib/modules/$(uname -r)/build/include/uapi/`, and is strictly a kernel header that should not be introduced into the userspace code. I see that in this repo, the reason <drm/drm.h> is used is that the library needs its macro definition and some other struct defs. In such case, <libdrm/drm.h> should be used, which is exactly the reason libdrm exists.
> 3. For a more concrete example of libdrm is used as a replacement for the kernel header in userspace code, `xrt/src/runtime_src/core/edge/include/zynq_ioctl.h` is a good case.

I'm confused. UAPI headers are meant for user space code to use. It is interface between kernel and user code. Also, the user space code in this repository build and run just fine. The user space code also include this header so that it can interact with driver. Not sure why it does not work for you?

2024-07-22 22:17 UTC, xuwd1 commented
> > To justify my changes and explain in more detail:
> > 
> > 1. Yes I'm currently on `6.10.0-1-mainline`. I built this new version of the kernel specifically for this driver.
> > 2. I'm pretty sure it's not because I have missing headers. <drm/drm.h> is a kernel header which should reside in `/usr/lib/modules/$(uname -r)/build/include/uapi/`, and is strictly a kernel header that should not be introduced into the userspace code. I see that in this repo, the reason <drm/drm.h> is used is that the library needs its macro definition and some other struct defs. In such case, <libdrm/drm.h> should be used, which is exactly the reason libdrm exists.
> > 3. For a more concrete example of libdrm is used as a replacement for the kernel header in userspace code, `xrt/src/runtime_src/core/edge/include/zynq_ioctl.h` is a good case.
> 
> I'm confused. UAPI headers are meant for user space code to use. It is interface between kernel and user code. Also, the user space code in this repository build and run just fine. The user space code also include this header so that it can interact with driver. Not sure why it does not work for you?

The current design will not build for any Arch installation, not just me. I see that uapi interfaces are indeed designed to appear in userspace codes, but only when they leave the kernel header tree, just like <libdrm/drm.h> actually keeps in sync with <drm/drm.h>. Actually, by checking the compiler system include pathes:
```
/usr/lib/gcc/x86_64-pc-linux-gnu/14.1.1/../../../../include/c++/14.1.1
 /usr/lib/gcc/x86_64-pc-linux-gnu/14.1.1/../../../../include/c++/14.1.1/x86_64-pc-linux-gnu
 /usr/lib/gcc/x86_64-pc-linux-gnu/14.1.1/../../../../include/c++/14.1.1/backward
 /usr/lib/gcc/x86_64-pc-linux-gnu/14.1.1/include
 /usr/local/include
 /usr/lib/gcc/x86_64-pc-linux-gnu/14.1.1/include-fixed
 /usr/include
```
You could clearly see that kernel headers are not there. Forcing the compiler to include ".../uapi/include/" would eventually cause the compiler to emit a warning from the kernel source:
```
/usr/lib/modules/6.10.0-1-mainline/build/include/uapi/linux/types.h:10:2: warning: #warning "Attempt to use kernel headers from user space, see https://kernelnewbies.org/KernelHeaders"
```

Anyway, the only reasonable explanation to me is that, unlike Arch, Ubuntu might have pre-copied all those drm headers directly under `/usr/include` and thus you find the code builds well in your production environment. And I would still insist my opinion that the current design should be changed, especially considering that the `xrt` codes have already adopted it.  If you did not like these changes, then I would just separately maintain a patch, and revert the changes made in that header.

2024-07-22 23:08 UTC, mamin506 commented
Hi @xuwd1 , if you built that kernel, there should be a linux-libc-dev package. You should install that package as well.

After that, you should be able to see,
``` shell
$find /usr/include/ -name drm.h
/usr/include/drm/drm.h
/usr/include/libdrm/drm.h
```

You don't need to include "uapi/" and compile also don't need to aware of this path.
In the user space code, just "#include drm/drm.h".

If you don't see linux-libc-dev package, please follow this step "https://github.com/amd/xdna-driver?tab=readme-ov-file#linux-compilation-and-installation" to build your kernel.

2024-07-22 23:32 UTC, xuwd1 commented
> Hi @xuwd1 , if you built that kernel, there should be a linux-libc-dev package. You should install that package as well.
> 
> After that, you should be able to see,
> 
> ```shell
> $find /usr/include/ -name drm.h
> /usr/include/drm/drm.h
> /usr/include/libdrm/drm.h
> ```
> 
> You don't need to include "uapi/" and compile also don't need to aware of this path. In the user space code, just "#include drm/drm.h".
> 
> If you don't see linux-libc-dev package, please follow this step "https://github.com/amd/xdna-driver?tab=readme-ov-file#linux-compilation-and-installation" to build your kernel.

Hi. Thanks for your advice, but sadly that is a distro specific thing. Actually, querying the arch database for `drm.h` has the following result:
```
core/linux-headers 6.9.10.arch1-1 [installed]
    usr/lib/modules/6.9.10-arch1-1/build/include/uapi/drm/drm.h
core/linux-lts-headers 6.6.40-1
    usr/lib/modules/6.6.40-1-lts/build/include/uapi/drm/drm.h
extra/aarch64-linux-gnu-linux-api-headers 6.7-1
    usr/aarch64-linux-gnu/include/drm/drm.h
extra/hyprland 0.41.2-2
    usr/include/hyprland/wlroots-hyprland/backend/drm/drm.h
    usr/include/hyprland/wlroots-hyprland/wlr/backend/drm.h
extra/kernel-headers-musl 4.19.88-2
    usr/lib/musl/include/drm/drm.h
extra/libdrm 2.4.122-1 [installed]
    usr/include/libdrm/drm.h
extra/linux-hardened-headers 6.9.9.hardened1-1
    usr/lib/modules/6.9.9-hardened1-1-hardened/build/include/uapi/drm/drm.h
extra/linux-rt-headers 6.7.0.6.realtime1-4
    usr/lib/modules/6.7.0.6.realtime1-4-rt/build/include/uapi/drm/drm.h
extra/linux-rt-lts-headers 6.6.23.28.realtime1-4
    usr/lib/modules/6.6.23.28.realtime1-4-rt-lts/build/include/uapi/drm/drm.h
extra/linux-zen-headers 6.9.10.zen1-1 [installed]
    usr/lib/modules/6.9.10-zen1-1-zen/build/include/uapi/drm/drm.h
extra/mesa 1:24.1.3-1 [installed: 1:24.1.4-2]
    usr/include/d3dadapter/drm.h
extra/riscv64-linux-gnu-linux-api-headers 6.8-1
    usr/riscv64-linux-gnu/include/drm/drm.h
extra/wlroots 0.18.0-1
    usr/include/wlroots-0.18/wlr/backend/drm.h
extra/wlroots0.17 0.17.4-1
    usr/include/wlroots0.17/wlr/backend/drm.h
extra/zig 0.13.0-1
    usr/lib/zig/libc/include/any-linux-any/drm/drm.h
```

2024-07-22 23:46 UTC, xuwd1 commented
Now reverted the changes made to `amdxdna_accel.h` header, please review the current version. I'll just keep the separate patch in AUR then.

2024-07-23 02:27 UTC, maxzhen approved these changes

2024-07-23 02:27 UTC, merged