enhance mailbox_polling
amd/xdna-driver pull request #204
Opened 2024-08-15 22:56 UTC by mamin506

Enhance the mailbox_polling parameter. 

In before, mailbox_polling is a switch, it switch mailbox as polling base or interrupt base.

After this change,
when mailbox_polling is 0, this is default, mailbox working on interrupt mode.
when mailbox_polling > 0, mailbox will check message in every 'mailbox_polling' miliseconds.
when mailbox_polling < 0, mailbox will be a busy polling. It will call schedule() to yield CPU to avoid soft lock warning. Thanks for Linux kernel scheduler, this will not consume 100% CPU when nothing is running.

``` shell
# Interrupt mode
$ sudo modprobe amdxdna

# Busy polling mode
$ sudo modprobe amdxdna mailbox_polling=-1

# Interval polling mode
$ sudo modprobe amdxdna mailbox_polling=1             # poll every 1 ms
$ sudo modprobe amdxdna mailbox_polling=100        # poll every 100 ms
```

2024-08-15 23:03 UTC, xdavidz approved these changes

2024-08-15 23:57 UTC, maxzhen requested changes
Linux kernel scheduler will not help here. We're burning CPU power for nothing if there is no outstanding command. We should poll only when we have outstanding commands.

2024-08-16 03:21 UTC, xdavidz commented
> Linux kernel scheduler will not help here. We're burning CPU power for nothing if there is no outstanding command. We should poll only when we have outstanding commands.

Maybe the way we use in the XRT scheduler is a good way? Like poll a little while right after submit a command and then wait for interrupt.

2024-08-16 22:25 UTC, mamin506 commented
> > Linux kernel scheduler will not help here. We're burning CPU power for nothing if there is no outstanding command. We should poll only when we have outstanding commands.
> 
> Maybe the way we use in the XRT scheduler is a good way? Like poll a little while right after submit a command and then wait for interrupt.

This change will keep the interrupt code path unchanged. The interrupts from NPU are not a problem at the moment. Let's do polling + interrupt when interrupt storm happens.

2024-08-16 22:28 UTC, mamin506 commented
I have updated the implementation of busy polling mode.
1. Create per device kthread, polld, to do busy polling, instead of creating kthread for each hardware context.
2. Once all mbox channels are idle, the polld kthread will sleep and wait.

2024-08-16 22:53 UTC, maxzhen approved these changes

2024-08-16 22:54 UTC, merged