Coverity Scan issues CID-65554, 481888, 48193
amd/xdna-driver pull request #312
Opened 2024-11-19 19:09 UTC by hlaccabu

Fixing small issues found by coverity scan, all located in src/shim/
Uncaught exception in hwctx.cpp, parse warning in bo.cpp, AUTO_CAUSES_COPY in kmq/bo.cpp

2024-11-19 22:47 UTC, xdavidz commented on src/shim/bo.cpp
> +alloc_drm_bo(const shim_xdna::pdev& dev, uint32_t type, void* buf, size_t size)
I'd keep the amdxdna_bo_type here for this api even it is prviate anonymous namespace.

And cast it to u32 at line16. Does that make sense?

2024-11-19 22:54 UTC, hlaccabu commented on src/shim/bo.cpp
> +alloc_drm_bo(const shim_xdna::pdev& dev, uint32_t type, void* buf, size_t size)
I tried it, the compiler doesn't like it it won't build that way.

2024-11-19 23:23 UTC, keryell requested changes
It would be great to have commit messages that make sense for an open-source project.

2024-11-19 23:31 UTC, xdavidz commented on src/shim/bo.cpp
> +alloc_drm_bo(const shim_xdna::pdev& dev, uint32_t type, void* buf, size_t size)
> I tried it, the compiler doesn't like it it won't build that way.

this should work:
.type = static_cast<uint32_t>(type),

2024-11-20 01:35 UTC, keryell approved these changes
Thanks!

2024-11-20 22:25 UTC, xdavidz approved these changes

2024-11-21 20:56 UTC, merged