driver: Enable AIE preemption
amd/xdna-driver pull request #319
Opened 2024-12-05 18:01 UTC by NishadSaraf

Enable AIE preemption and add interface to force preemption.

2024-12-05 18:31 UTC, maxzhen commented
I don't see you update xrt submodule. Do you have any dependency on newer version of XRT?

2024-12-05 18:39 UTC, NishadSaraf commented
> I don't see you update xrt submodule. Do you have any dependency on newer version of XRT?

This PR doesn't depend on XRT latest. The existing version works fine.

2024-12-05 22:07 UTC, mamin506 requested changes
The two new RT config is not in NPU1. This is okay and good. aie2_runtime_cfg() will skip it on NPU1.

But the ndev->force_preempt_enabled flag was set for NPU1 as well. And it can be get by ioctl(). If this is not supported in NPU1, please keep ndev->force_preemption_enabled as 0" to avoid confusing.

2024-12-05 22:07 UTC, mamin506 commented on src/include/uapi/drm_local/amdxdna_accel.h
> + *						 0 implies disabled
Please fix indentation.
```suggestion
 * @force_preempt_state: 1 implies force preemption is enabled.
 *                        0 implies disabled
```

2024-12-05 22:07 UTC, mamin506 commented on src/include/uapi/drm_local/amdxdna_accel.h
> + *						 0 implies disabled
Ditto.

2024-12-05 22:07 UTC, mamin506 commented on src/driver/amdxdna/amdxdna_ctx.h
> +};
This enum defined the value of priotity in `struct amdxdna_qos_info`. Move this to before `struct amdxdna_qos_info` in amdxdna_accel.h  is better.

Remove prefix "XRT_" and "xrt_". Use "qos_" and "QOS_" is good enough.
XRT_QOS_DEFAULT_PRIORITY is missing in the comment. 
In the comment you can say "Enum for priority in application's QoS"

2024-12-05 22:07 UTC, mamin506 commented on src/driver/amdxdna/amdxdna_ctx.h
> +};
This is defined by firmware. Please move it to aie2_msg_priv.h

2024-12-05 22:07 UTC, mamin506 commented on src/driver/amdxdna/aie2_message.c
> +
Can we set ndev->force_preempt_enabled flag in `aie2_set_force_preempt_state()` in aie2_pci.c? This function is not needed.

2024-12-05 22:07 UTC, mamin506 commented on src/driver/amdxdna/aie2_message.c
> +							   &hwctx->fw_ctx_id);
Indentation..

2024-12-05 22:07 UTC, mamin506 commented on src/driver/amdxdna/aie2_message.c
> +			XDNA_ERR(ndev->xdna, "Runtime config failed");
```suggestion
			XDNA_ERR(ndev->xdna, "Config force preemption failed");
```

2024-12-05 22:07 UTC, mamin506 commented on src/driver/amdxdna/aie2_pci.c
> +bool disable_fine_preemption = 0;
Do not initialize global variable to "0". It is by default 0.

Since this is 'bool' type,
 ```suggestion
bool disable_fine_preemption = false;
```

2024-12-05 22:07 UTC, mamin506 commented on src/driver/amdxdna/aie2_pci.c
> +		ret = aie2_runtime_cfg(ndev, AIE2_RT_CFG_FINE_PREEMPTION, 0);
```suggestion
	if (disable_fine_preemption) {
		ret = aie2_runtime_cfg(ndev, AIE2_RT_CFG_FINE_PREEMPTION, NULL);
```
The third argument is a pointer, use "NULL" instead.

One question, when the third argument is NULL. `aie2_runtime_cfg()` use the default value.
The default is in npu4_regs.c, as below.
{ 12, 1, AIE2_RT_CFG_FINE_PREEMPTION },

I want to confirm that if "1" means fine preemption is disabled? Is so, can you add comment in npu4_regs.c like other runtime configures?

2024-12-05 22:07 UTC, mamin506 commented on src/driver/amdxdna/aie2_pci.c
> +			XDNA_ERR(ndev->xdna, "Runtime config failed");
```suggestion
			XDNA_ERR(ndev->xdna, "Disable fine preemption failed");
```

2024-12-05 22:07 UTC, mamin506 commented on src/driver/amdxdna/aie2_pci.h
> +	bool			force_preempt_enabled;
Indentation..

2024-12-05 22:07 UTC, mamin506 commented on src/shim/device.cpp
> +    };
Indentation should be 2 spaces.

2024-12-05 22:07 UTC, mamin506 commented on src/driver/amdxdna/npu4_regs.c
> +	{ 13, 0, AIE2_RT_CFG_FORCE_PREEMPTION },
Add comment like other entries.

2024-12-06 08:44 UTC, NishadSaraf commented
> Quote reply
> Reference

Hi @mamin506, Thanks for the quick review. I have addressed all the review comments. Please let me know if missed anything. Thanks :)

2024-12-06 17:06 UTC, mamin506 approved these changes
LGTM

2024-12-07 00:43 UTC, maxzhen commented
retest this please

2024-12-09 23:44 UTC, maxzhen commented
retest this please

2024-12-09 23:44 UTC, maxzhen approved these changes

2024-12-10 22:59 UTC, mamin506 commented
retest this please

2024-12-10 23:29 UTC, merged