enable xrt_test.cpp
amd/xdna-driver pull request #98
Opened 2024-05-20 23:26 UTC by xdavidz

trim xrt test into a separate file, now only xrt vadd is in this test file.

2024-05-21 06:34 UTC, mamin506 approved these changes

2024-05-21 15:43 UTC, maxzhen requested changes
The change seems to be incomplete. We can discuss offline.

2024-05-22 22:05 UTC, xdavidz commented
> The change seems to be incomplete. We can discuss offline.

Tested shim_test and xrt_test. Both still working.

xrt_test still requires lib_coreutil, I think it is expected. Please let me know if the xrt_test.cpp is expected.

shim_test has dependencies on lib_coreutil by some existing test cases, we can use a spearate PR to clean this up.

2024-05-22 22:24 UTC, maxzhen approved these changes

2024-05-24 04:42 UTC, xdavidz commented
now it passes without any shim layer lib included from xrt_test

2024-05-24 15:50 UTC, maxzhen commented on test/xrt_test/CMakeLists.txt
> +
These compilation definitions can be removed. They impact shim level API definitions. XRT application does not need to specify them.

2024-05-24 15:55 UTC, merged